version: "3"
services:
  db:
    image: postgres
    ports:
      - 54322:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db:/data/postgres

  web:
    build:
      context: .
    restart: always
    ports:
      - 8001:8000
    env_file: .env
    command: 'sh -c "make migrate && make run"'
    volumes:
      - ./:/app
    depends_on:
      - db
